# state.py
import operator
from typing import Annotated, TypedDict, List
from langchain_core.messages import BaseMessage

class AgentState(TypedDict):
    messages: Annotated[list[BaseMessage], operator.add]
    next: str
    code_review_count: int # NEW: Counter for code review iterations
    generated_code: str # NEW: To store the code generated by the agent
    code_review_feedback: str # NEW: To store feedback from the review agent